### PR TITLE
menu-style-fix

### PR DESCRIPTION
**Pull request by JasonLG1979**
Fixes https://github.com/LinxGem33/Arc-Menu/issues/6

### CODE REVIEW

**Comment by LinxGem33** [comment]
really appreciate you taking the time to contribute, would it be ok to credit you as a contributor?

looking at the code it looks good i know what you mean now after viewing the code.

**Comment by JasonLG1979** [comment]
Glad to help. Yep, you should refer to stuff as em's as much as possible so it scales across themes. Sure I'd love to be listed as a contributor.

**Comment by LinxGem33** [comment]
thank you again, and i will credit you now on main page, also if you find anything else that you think you could contribute via a pull request please don’t hesitate.

kind regards

**Comment by JasonLG1979** [comment]
Will do. I know how much a PITA writing extensions is. I'm sure we can learn from each other. After all that's the only way to figure it out since there really isn't any docs,lol!!!

**Comment by LinxGem33** [comment]
your absolutely right lol, and thank you again.

**Pull request merged**
