### PR TITLE
Async Icons

### PR DESCRIPTION
**Pull request by JasonLG1979**
Asynchronously set an icon and handle errors.

setIconAsync takes an icon which you want to change, a Gio.File representing an image file(local or remote) that may or may not exist, and a fallback icon name to use if the file does not exist. It then asynchronously loads the contents into a gicon if successful otherwise it sets the icon to the fallback icon name.

This removes the need for blocking I/O when loading images from a file.

### CODE REVIEW

**Comment by LinxGem33** [comment]
quality really nice, just reviewed, I’m still fixing the translations bug lol hopefully should get it fixed, also just uploaded v2 of Arc menu to extensions.gnome.org, ill add this to your growing contribution list on main page, thank you your definitely a great help cant thank you enough for taking the time.

**Comment by JasonLG1979** [comment]
No problem. That's recycled from https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

No one follows the MPRIS spec and a lot of players send remote and/or malformed file paths. I needed a way to load images with error handling. Doing blocking I/O on a remote image would have locked up the shell for a up to a couple secs. No good,lol!!!

**Comment by JasonLG1979** [comment]
Next up I think I might make the widget code a little more modular. Particularly with the power and what not buttons there's a lot of code duplication.

**Comment by LinxGem33** [comment]
i really appreciate you doing this I’m learning fast about JavaScript by your changes etc and extensions and your not wrong about extensions being a pain i made one typo in the syntax and the extension wouldn’t load it took me an hour to figure out lol.

**Comment by JasonLG1979** [comment]
I'm very much a js noob myself(maybe 6 months playing with it?). I'm more of a Python guy but I'm pretty familiar with GLib stuff because of PyGObject so I think that helps. I also use https://lazka.github.io/pgi-docs/ and try to translate it to Gjs because there aren't really any good Gjs docs.

I generally use GNOME logs to view the exception when something doesn't load.

**Comment by LinxGem33** [comment]
will defiantly look that up I’ve only just started using gnome logs for error exception i was using looking glass before but i had one or two issues with it, thank you again.

kind regards

**Pull request merged**
