### PR TITLE
controller.js: Unscale the menu icon on HiDPI monitors

### PR DESCRIPTION
**Pull request by lexruee**
This pull request should fix the icon size issue on HiDPI monitors (see #117 and #143).

The idea behind the fix is to unscale the menu icon on HiDPI monitors so users can set the right size.
Unfortunately, I don't own a fancy HiDPI monitor so I can't test it on real hardware :cry:.

@jbuisine , @ljhui: Could you please test this this pull request and report back if the issue still persists. Thanks in advance :smile:.

### CODE REVIEW

**Comment by ljhui** [comment]
it behaves inverse as I report ,I set icon size to 22px，scale factor to 2, when I launch my laptop, it show picture as behind
ex1
but if I lock my PC and then unlock to relogin my pc ,the icon size becomes small
ex2
morever, if I use ALT+F2 to restart gnome-shell ,the icon size will change from big to small .
if the icon show small, then I have change size from 22px to 43px , then the icon looks well as I launch.
it seems the highdpi window scale factor not always work, I look your commit code, change
` let size = iconSize  / scaleFactor;`
to 
` let size = iconSize  ;`
I remove the scaleFactor, I am not familiar with the code, just a try  ,but it fix my problem actually.

**Comment by lexruee** [comment]
@ljhui 
Thanks for your feedback and observation. Interesting, so it seems that it's not possible to simulate the HiDPI monitor behaviour on a normal monitor (1080p) by using a window scaling factor of 2. For example, the code `let size = iconSize / scaleFactor;` fixed the issue on my "simulated" HiDPI setup.

As you suggested, I removed the HiDPI scaling code in the latest commit (05fef54).

**Comment by jbuisine** [comment]
Sorry, but it does not seem to work for me. Anyone else can test this pull request ?

**Comment by lexruee** [comment]
Hmm, I close this pull request as I can't really test any code that should provide HiDPI support.
I hope an extension developer comes along who can help us to add support for HiDPI. Maybe we should create a github issue called "HiDPI Support - Need help".

@ljhui Short question: Can you push your changes on github that wokred for your setup or even make a pull request against the development branch?

**Pull request closed without merging**
