### PR TITLE
add Arabic translation 

### PR DESCRIPTION
**Pull request by madaramost**
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the Arc Menu package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Arc Menu\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-07-09 16:20+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: Madaramost <madaramost@gmail.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: ar\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: prefs.js:76
msgid "Behaviour"
msgstr "الأداء"

#: prefs.js:85
msgid "Disable activities hot corner"
msgstr "تعطيل نوافذ الزوايا"

#: prefs.js:107
msgid "Set menu hotkey"
msgstr "زر إظهار النوافذ النشطة"

#: prefs.js:113
msgid "Undefined"
msgstr "بدون"

#: prefs.js:114
msgid "Left Super Key"
msgstr "الأيسر Super زر"

#: prefs.js:115
msgid "Right Super Key"
msgstr "الأيمن Super زر"

#: prefs.js:127
msgid "Enable custom menu keybinding"
msgstr "تمكين إظهار القائمة بواسطة لوحة المفاتيح"

#: prefs.js:134
msgid "Syntax: <Shift>, <Ctrl>, <Alt>, <Super>"
msgstr "<Shift>, <Ctrl>, <Alt>, <Super> :الرموز"

#: prefs.js:175
msgid "Appearance"
msgstr "المظهر"

#: prefs.js:184
msgid "Customize menu button appearance"
msgstr "ضبط مظهر زر القائمة"

#: prefs.js:194
msgid "Icon"
msgstr "الأيقونة"

#: prefs.js:195
msgid "Text"
msgstr "كتابة"

#: prefs.js:196
msgid "Icon and Text"
msgstr "أيقونة ثم كتابة"

#: prefs.js:197
msgid "Text and Icon"
msgstr "كتابة ثم أيقونة"

#: prefs.js:222
msgid "Menu position in panel"
msgstr "مكان القائمة في الشريط"

#: prefs.js:229
msgid "Left"
msgstr "يسار"

#: prefs.js:232
msgid "Center"
msgstr "وسط"

#: prefs.js:236
msgid "Right"
msgstr "يمين"

#: prefs.js:279
msgid "Button appearance"
msgstr "مظهر زر القائمة"

#: prefs.js:291
msgid "Text for the menu button"
msgstr "النص الذي يظهر على زر القائمة"

#: prefs.js:297
msgid "System text"
msgstr "(إفتراضي (النظام"

#: prefs.js:300
msgid "Custom text"
msgstr "إختيار نص"

#: prefs.js:320
msgid "Set custom text for the menu button"
msgstr "إختيار نص لزر القائمة"

#: prefs.js:340
msgid "Enable the arrow icon beside the button text"
msgstr "تمكين النقر بالسهم على نص الايقونة"

#: prefs.js:362
msgid "Select icon for the menu button"
msgstr "إختيار أيقونة لزر القائمة"

#: prefs.js:372
msgid "Please select an image icon"
msgstr "الرجاء إختيار صورة الأيقونة"

#: prefs.js:387
msgid "Arc Menu Icon"
msgstr "الإفتراضية"

#: prefs.js:388
msgid "System Icon"
msgstr "أيقونة النظام"

#: prefs.js:389
msgid "Custom Icon"
msgstr "إختيار مخصص"

#: prefs.js:404
msgid "Icon size"
msgstr "حجم الأيقونة"

#: prefs.js:404
msgid "default is"
msgstr "الحجم الإفتراضي"

#: prefs.js:448
msgid "About"
msgstr "حول"

#: prefs.js:477
msgid "Arc-Menu"
msgstr "Arc-Menu"

#: prefs.js:482
msgid "version: "
msgstr "النسخة"

#: prefs.js:490
msgid "Webpage"
msgstr "موقع البرنامج"

#: menu.js:130
msgid "Activities Overview"
msgstr "النوافذ النشطة"

#: menu.js:154
msgid "Power Off"
msgstr "إيقاف التشغيل"

#: menu.js:179
msgid "Log Out"
msgstr "خروج"

#: menu.js:204
msgid "Suspend"
msgstr "إيقاف آني"

#: menu.js:235
msgid "Lock"
msgstr "إغلاق"

#: menu.js:263
msgid "Back"
msgstr "تراجع"

#: menu.js:555
msgid "Favorites"
msgstr "المفضّلة"

#: menu.js:721
msgid "Applications"
msgstr "البرامج"

#: menu.js:976
msgid "Home"
msgstr "المنزل"

#: menu.js:1041
msgid "Type to search..."
msgstr "...بحث"

#: menu.js:1130
msgid "Software"
msgstr "برامج"

#: menu.js:1134
msgid "Settings"
msgstr "الإعدادات"

#: menu.js:1138
msgid "Tweak Tool"
msgstr "تويك تول"

### CODE REVIEW

**Comment by lexruee** [comment]
@madaramost 
Hey! Thank you for taking the time and creating the Arabic translation :-).

In order to add your translations, we need a pull-request against the `Development-branch` that contains a po file named `ar.po` with your Arabic translation.

Overall, we follow the "fork-and-pull" Git workflow.
1. Fork the repo on GitHub
2. Clone the project to your own machine
3. Commit changes to your own branch such as `add-arabic-translation`
4. Push your work back up to your fork
5. Submit a Pull request against the `Development-branch` so that we can review your changes

**Comment by madaramost** [comment]
done now.

**Comment by LinxGem33** [comment]
you now need to make a new pull-request with the translation.

kind regards

**Comment by madaramost** [comment]
done

**Pull request closed without merging**
