### PR TITLE
icon: symbolic

### PR DESCRIPTION
**Pull request by itmitica**
arc-menu-symbolic.svg

### CODE REVIEW

**Comment by LinxGem33** [comment]
thank you really appreciate your PR.

**Comment by lexruee** [comment]
This pull request introduced on the development branch a tiny UI bug :-). The adapated Arc Menu Icon is not visible when I use the adapta-gtk-theme, or more precisely the adapta gnome shell theme. The following is a screenshot of the current development branch when I use the adapta gnome shell theme.

**Shell theme: adapta**
arc-menu-icon-adapta-gtk-theme-part

**Comment by itmitica** [comment]
I don't have this issue. Here it is how it looks with the default shell theme, a dark theme vs. my theme, slimUG, a light theme, transparent actually. The *symbolic* directive works as expected. My guess is the adapta theme is at fault here.
arc-menu-symbolic

**Comment by itmitica** [comment]
@LinxGem33 , @lexruee 

For icon *symbolic*, style class needs to be *style_class: 'system-status-icon'*. This should solve the issues.

The *_setButtonIcon: function()* section of *controller.js* should be changed accordingly. I have the Force Quit extension modified as well, with a similar *symbolic* icon, and it works with **adapta** (see screenshot), but the code is more clearer:
```
    let icon = new St.Icon({ icon_name: 'force-quit-symbolic',
                             style_class: 'system-status-icon' });

![symbolic-system](https://user-images.githubusercontent.com/1570477/28241749-f4222cae-69a2-11e7-9271-a0b6cb040d61.jpg)

**Comment by lexruee** [comment]
@itmitica 
You are right. This is really an adapta-theme specific issue.

**Comment by itmitica** [comment]
Yes, it has to do with `popup-menu-icon` style applied to arc menu button.

I located the lines responsible in adapta directory. Commenting this lines fixes the issue.

`/usr/share/themes/Adapta-Eta/gnome-shell/gnome-shell.css`

```
#panelApplications StIcon, #panelApplications:hover StIcon, #panelApplications:focus StIcon, #panelApplications:active StIcon, #panelApplications:checked StIcon { color: transparent; }

#panelApplications StIcon.popup-menu-icon { min-width: 20px; padding: 0 2px; background-image: url("assets/show-apps-panel.svg"); background-size: 32px 32px; background-position: center center; transition-duration: 0s; }

#panelApplications:hover StIcon.popup-menu-icon, #panelApplications:focus StIcon.popup-menu-icon, #panelApplications:active StIcon.popup-menu-icon, #panelApplications:checked StIcon.popup-menu-icon { background-image: url("assets/show-apps-panel-hover.svg"); transition-duration: 0s; }

```

**Comment by lexruee** [comment]
@itmitica 
In the upstream repository, I think the problem is probably here:
https://github.com/adapta-project/adapta-gtk-theme/blob/ca0712e7e3f99b1d910f5f175271007418c9afd0/shell/sass/gnome-shell/3.24/_common.scss#L811

Note: I'm not a GNOME Shell CSS or theming expert ;-)

**Comment by itmitica** [comment]
Yes, that's it.

Somehow, `popup-menu-icon` for the arc menu button should be changed to something else.

**Comment by LinxGem33** [comment]
@itmitica @lexruee 

hopefully we will work together to rectify this issue thanks again @itmitica for taking the time to look into this issue its really appreciated.

**Pull request merged**
